//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ATM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATMEntities : DbContext
    {
        public ATMEntities()
            : base("name=ATMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Amount> tbl_Amount { get; set; }
        public virtual DbSet<tbl_DropdownType> tbl_DropdownType { get; set; }
        public virtual DbSet<tbl_eventlog> tbl_eventlog { get; set; }
        public virtual DbSet<tbl_Exception_Logs> tbl_Exception_Logs { get; set; }
        public virtual DbSet<tbl_LoginHistory> tbl_LoginHistory { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_UserRights> tbl_UserRights { get; set; }
        public virtual DbSet<tbl_UserRole> tbl_UserRole { get; set; }
    }
}
