//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ATM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserRights
    {
        public int UserRightID { get; set; }
        public Nullable<int> UserRoleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AllowedTransactionID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastChangedOn { get; set; }
        public string LastChangedBy { get; set; }
        public bool DisplayPO { get; set; }
        public bool ModifyPO { get; set; }
        public bool CreatePO { get; set; }
        public bool DisplayIBD { get; set; }
        public bool ModifyIBD { get; set; }
        public bool CreateIBD { get; set; }
        public bool DisplayStoIssue { get; set; }
        public bool ModifyStoIssue { get; set; }
        public bool CreateStoIssue { get; set; }
        public bool DisplayStoRecieve { get; set; }
        public bool ModifyStoRecieve { get; set; }
        public bool CreateStoRecieve { get; set; }
        public bool DisplaySalesOut { get; set; }
        public bool ModifySalesOut { get; set; }
        public bool CreateSalesOut { get; set; }
        public bool DIsplaySalesIn { get; set; }
        public bool ModifySalesIn { get; set; }
        public bool CreateSalesIn { get; set; }
        public bool DisplayInternal { get; set; }
        public bool ModifyInternal { get; set; }
        public bool CreateInternal { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_UserRole tbl_UserRole { get; set; }
    }
}
