//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ATM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Amount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Amount()
        {
            this.tbl_Exception_Logs = new HashSet<tbl_Exception_Logs>();
        }
    
        public int AmountID { get; set; }
        public string AmountDescription { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Balance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Exception_Logs> tbl_Exception_Logs { get; set; }
    }
}
